version: '3.8'
services:
  app:
    build: .
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./logs:/app/logs
    environment:
      - JAVA_TOOL_OPTIONS=-Duser.language=ru -Duser.country=RU
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"